-- psql -U dunder_mifflin -d relentless -f ./migrations/001.do.create_relentless_goals.sql

CREATE TABLE annual_goals (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content TEXT NOT NULL,
  complete BOOLEAN DEFAULT false,
  date_created TIMESTAMP DEFAULT now() NOT null,
  date_modified TIMESTAMP DEFAULT now() NOT null
);

CREATE TABLE monthly_goals (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    complete BOOLEAN DEFAULT false,
    annual_goal INTEGER REFERENCES annual_goals(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT null,
    date_modified TIMESTAMP DEFAULT now() NOT null
);

CREATE TABLE weekly_goals (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    complete BOOLEAN DEFAULT false,
    monthly_goal INTEGER REFERENCES monthly_goals(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT null,
    date_modified TIMESTAMP DEFAULT now() NOT null
);